### PR TITLE
Make nginx IP configurable

### PR DESCRIPTION
**Pull request by mdelillo**
Make it possible for nginx to not listen on all interfaces.

@chhhavi @mdelillo

### CODE REVIEW

**Comment by zvance** [comment]
Hey @mdelillo, could you say more about the need for this? Is this security related?

**Comment by mdelillo** [comment]
Hi @zvance, we are using this to have nginx listen on localhost. The use case is to have multiple services running co-located on a single VM (for example, on PCF Dev), but only having them accessible through the public routes for security.

**Comment by zvance** [comment]
Thanks @mdelillo. We've scheduled this for a later date.

**Comment by edwardecook** [comment]
@mdelillo thanks for the PR, apologies for the absurdly long time it took for this to be merged.

**Pull request merged**
